"""
TK 06.01.2026
"""
from analyzeABM.constants import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def plot_celldata(cell_csvpath, title="Tumor plot", xmin=-1000, xmax=1000, ymin=-1000, ymax=1000):
    usecols = [1, 2, 3, 4, 5]

    scale = (6.4 / (max(xmax - xmin, ymax - ymin) * 2 + 1) * 300.) ** 2
    cells = pd.read_csv(cell_csvpath, usecols=usecols, names=["cell_type", "x", "y", "radius", "state"])
    cells["s_scaled"] = scale * cells["radius"]

    # Maybe change this so that cancer cells get drawn LAST
    cells.plot.scatter("x", "y", c="state", s="s_scaled",
                       colormap=cell_cmap, vmin=-0.5, vmax=11.5,
                       xlim=[xmin, xmax], ylim=[ymin, ymax])
    f = plt.gcf()
    f.set_dpi(300)
    [pax, cax] = f.get_axes()

    pax.set(xlabel="x-coordinate", ylabel="y-coordinate", title=title)
    cax.set_ylabel('')
    cax.set_ylim(-0.5, num_cell_types - 0.5)
    cax.set_yticks(np.arange(0, num_cell_types), labels=cell_labels)

    return f


def plot_ts(ts_df, types_to_plot=None,
            title="Time series data", ax=None, normalize=False, err_type=("sd", 1), linestyle="solid"):
    """
    Use to plot timeseries data obtained with retrieve_ts()
    :param ts_df: DataFrame from retrieve_ts()
    :param types_to_plot: what celltypes to plot using LOWERCASE abbreviations
    :param title: Title of plot
    :param ax: Axis to plot on if it exists
    :param normalize: Whether to normalize to t = 0
    :param err_type: What type of error to plot over replicates
    :param linestyle: Type of line to use
    :return: Returns matplotlib Figure object
    """
    if types_to_plot is None:
        types_to_plot = ["m0", "m1", "m2", "c", "cd4_th", "cd4_treg", "cd8", "nk", "mdsc", "myeloid", "lymphoid",
                         "stromal"]

    melted = []

    for ctype in types_to_plot:
        if normalize:
            n_i = ts_df[ctype]["0"][0]
            ts_df[ctype] = ts_df[ctype] / n_i
        melt = ts_df[ctype].melt(var_name='Replicate', value_name=ctype, ignore_index=False)
        melt["Time"] = melt.index
        melted.append([ctype, melt])

    if ax is None:
        fig, ax = plt.subplots()

    for entry in melted:
        sns.lineplot(data=entry[1], x="Time", y=entry[0], errorbar=err_type, ax=ax, linestyle=linestyle)

    if "radius" != types_to_plot:
        ax.set(xlabel="Time (hr)", ylabel="No. cells", title=title)
    else:
        ax.set(xlabel="Time (hr)", ylabel="Radius (um)", title=title)

    f = plt.gcf()

    return f


def plot_kill_ts(ts_df, types_to_plot=None, title="Time series data", ax=None, normalize=False, err_type=("sd", 1)):
    """
    Plots data from retrieve_kill_ts()
    :param ts_df: DataFrame generated by retrieve_kill_ts()
    :param types_to_plot: What types of killing to plot (age, cd8, &or nk)
    :param title: Title of the plot
    :param ax: Ax to plot on if it exists
    :param normalize: Whether to normalize to t = 0
    :param err_type: Type of error to plot over replicates
    :return: Figure object
    """
    if types_to_plot is None:
        types_to_plot = ["age", "cd8", "nk"]
    melted = []

    for ctype in types_to_plot:
        if normalize:
            n_i = ts_df[ctype]["0"][0]
            ts_df[ctype] = ts_df[ctype] / n_i
        melt = ts_df[ctype].melt(var_name='Replicate', value_name=ctype, ignore_index=False)
        melt["Time"] = melt.index
        melted.append([ctype, melt])

    if ax is None:
        fig, ax = plt.subplots()

    for entry in melted:
        sns.lineplot(data=entry[1], x="Time", y=entry[0], errorbar=err_type, ax=ax)

    if "radius" != types_to_plot:
        ax.set(xlabel="Time (hr)", ylabel="No. cells killed", title=title)
    else:
        ax.set(xlabel="Time (hr)", ylabel="Radius (um)", title=title)

    f = plt.gcf()

    return f
